/*
Edit Notes
----------
1. ERDAT is now used as time stamp, which means ERZET is discarded
2. Follows VBAP, not VBAK
3. Removed German version of activities to simplify script
4. UDAT is now the combination of UDAT and UTIME
*/

DROP TABLE IF EXISTS "_CEL_O2C_VBAP_ACTIVITIES";
CREATE TABLE "_CEL_O2C_VBAP_ACTIVITIES" (
	"_CASE_KEY" VARCHAR(30)
    , "ACTIVITY" VARCHAR(200)
    , "EVENTTIME" DATETIME
    , "_SORTING" INTEGER
    , "USER_NAME" VARCHAR(100)
    , "USER_TYPE" VARCHAR(10)
    , "MANDT" VARCHAR(3)
    , "VBELN" VARCHAR(64)
    , "POSNR" VARCHAR(10)
);

-- Activity: Create Sales Order
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT 
    ,"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
    ,'Create Sales Order' AS "ACTIVITY"
    ,"VBAK"."ERDAT" AS "EVENTTIME"
    ,11 AS "_SORTING"
    ,"VBAK"."ERNAM" AS "USER_NAME"
    ,"USR02"."USTYP" AS "USER_TYPE"
    ,"VBAP"."MANDT" AS "MANDT"
    ,"VBAP"."VBELN" AS "VBELN"
    ,"VBAP"."POSNR" AS "POSNR"
FROM "VBAP"
    LEFT JOIN "VBAK" on 1=1
        AND "VBAP"."MANDT" = "VBAK"."MANDT"
        AND "VBAP"."VBELN" = "VBAK"."VBELN"
    LEFT JOIN "USR02" AS "USR02" ON
        "VBAK"."MANDT" = "USR02"."MANDT" AND
        "VBAK"."ERNAM" = "USR02"."BNAME";

-- Activity: Generate Delivery Document
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
	"VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
	,'Generate Delivery Document' AS "ACTIVITY"
	, "LIPS"."ERDAT" AS "EVENTTIME"
	, 71 AS "_SORTING"
	, "LIKP"."ERNAM" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	, "VBFA"."MANDT" AS "MANDT"
	, "VBFA"."VBELV" AS "VBELN"
	, "VBFA"."POSNV" AS "POSNR"
FROM "VBFA"
	JOIN "LIPS" AS "LIPS" ON 1=1
        AND "VBFA"."MANDT" = "LIPS"."MANDT"
		AND "VBFA"."VBELN" = "LIPS"."VBELN"
		AND "VBFA"."POSNN" = "LIPS"."POSNR" 
	JOIN "LIKP" AS "LIKP" ON 1=1
		AND "LIPS"."MANDT" = "LIKP"."MANDT"
		AND "LIPS"."VBELN" = "LIKP"."VBELN" 
        AND "LIPS"."ERDAT" IS NOT NULL   
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "LIKP"."MANDT" = "USR02"."MANDT"
		AND "LIKP"."ERNAM" = "USR02"."BNAME";

-- Activity: Release Delivery
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
	"VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
	,'Release Delivery' AS "ACTIVITY"
	, "CDHDR"."UDATE" AS "EVENTTIME"
	, 75 AS "_SORTING"
	, "CDHDR"."USERNAME" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	, "VBFA"."MANDT" AS "MANDT"
	, "VBFA"."VBELV" AS "VBELN"
	, "VBFA"."POSNV" AS "POSNR"
FROM "VBFA"
	JOIN "LIPS" AS "LIPS" ON 
		"VBFA"."MANDT" = "LIPS"."MANDT" AND
		"VBFA"."VBELN" = "LIPS"."VBELN" AND
		"VBFA"."POSNN" = "LIPS"."POSNR" 
	LEFT JOIN "CDPOS" AS "CDPOS" ON 1=1
		AND "CDPOS"."OBJECTID" = "LIPS"."MANDT" || "LIPS"."VBELN" || "LIPS"."POSNR"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "CDHDR"."MANDT" = "USR02"."MANDT"
		AND "CDHDR"."USNAM" = "USR02"."BNAME"
WHERE "VBFA"."VBTYP_V" = 'C' 
	AND "VBFA"."VBTYP_N" = 'J'
	AND "CDPOS"."TABNAME" = 'LIPS' AND "CDPOS"."FNAME" = "ABART" AND "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" = 6

-- Activity: Record Goods Issue (shipment)
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT DISTINCT
 	 "VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
 	,'Record Goods Issue' AS "ACTIVITY"
	,"VBFA"."ERDAT" AS "EVENTTIME"
	,80 +
	CASE
 	    WHEN "VBFA"."VBTYP_N" = 'R' THEN 1
 	END AS "_SORTING"
	,"MKPF"."USNAM" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBFA"."MANDT" AS "MANDT"
	,"VBFA"."VBELV" AS "VBELN"
	,"VBFA"."POSNV" AS "POSNR"
FROM "VBFA"
	LEFT JOIN "MKPF" AS "MKPF" ON 1=1
		AND "MKPF"."MANDT" = "VBFA"."MANDT"
		AND "MKPF"."MBLNR" = "VBFA"."VBELN"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "MKPF"."MANDT" = "USR02"."MANDT"
		AND "MKPF"."USNAM" = "USR02"."BNAME"
WHERE "VBFA"."VBTYP_V" = 'J' 
	AND "VBFA"."VBTYP_N" = 'R'

-- Activity: Create Billing Document/Send Invoice
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT DISTINCT
 	 "VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
 	,'Send Invoice' AS "ACTIVITY"
	,"VBFA"."ERDAT" AS "EVENTTIME"
	,90 AS "_SORTING"
	,"VBRK"."USNAM" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBFA"."MANDT" AS "MANDT"
	,"VBFA"."VBELV" AS "VBELN"
	,"VBFA"."POSNV" AS "POSNR"
FROM "VBFA"
	LEFT JOIN "VBRK" AS "VBRK" ON 1=1
		AND "VBRK"."MANDT" = "VBFA"."MANDT"
		AND "VBRK"."VBELN" = "VBFA"."VBELN"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "VBRK"."MANDT" = "USR02"."MANDT"
		AND "VBRK"."USNAM" = "USR02"."BNAME"
WHERE "VBFA"."VBTYP_V" = 'R' 
	AND "VBFA"."VBTYP_N" = 'M'


-- Activity: Receive Delivery Confirmation
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
	"VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
	,'Receive Delivery Confirmation' AS "ACTIVITY"
	, "CDHDR"."UDATE" AS "EVENTTIME"
	, 75 AS "_SORTING"
	, "CDHDR"."USERNAME" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	, "VBFA"."MANDT" AS "MANDT"
	, "VBFA"."VBELV" AS "VBELN"
	, "VBFA"."POSNV" AS "POSNR"
FROM "VBFA"
	JOIN "LIPS" AS "LIPS" ON 
		"VBFA"."MANDT" = "LIPS"."MANDT" AND
		"VBFA"."VBELN" = "LIPS"."VBELN" AND
		"VBFA"."POSNN" = "LIPS"."POSNR" 
	LEFT JOIN "CDPOS" AS "CDPOS" ON 1=1
		AND "CDPOS"."OBJECTID" = "LIPS"."MANDT" || "LIPS"."VBELN" || "LIPS"."POSNR"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "CDHDR"."MANDT" = "USR02"."MANDT"
		AND "CDHDR"."USNAM" = "USR02"."BNAME"
WHERE "VBFA"."VBTYP_V" = 'C' 
	AND "VBFA"."VBTYP_N" = 'J'
	AND "CDPOS"."TABNAME" = 'LIKP' AND "CDPOS"."FNAME" = "SPE_ACC_APP_STS" IS NULL AND "CDPOS"."VALUE_NEW" = 'C'


-- Activity: Clear Invoice
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT DISTINCT
 	 "VBFA"."MANDT" || "VBFA"."VBELV" || "VBFA"."POSNV" AS "_CASE_KEY"
 	,'Clear Invoice' AS "ACTIVITY"
	,"BSEG"."AUGDT" AS "EVENTTIME"
	,90 AS "_SORTING"
	,"VBRK"."USNAM" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBFA"."MANDT" AS "MANDT"
	,"VBFA"."VBELV" AS "VBELN"
	,"VBFA"."POSNV" AS "POSNR"
FROM "VBFA"
	LEFT JOIN "VBRK" AS "VBRK" ON 1=1
		AND "VBRK"."MANDT" = "VBFA"."MANDT"
		AND "VBRK"."VBELN" = "VBFA"."VBELN"
	LEFT JOIN "BKPF" AS "BKPF" ON 1=1
		AND "BKPF"."MANDT" = "VBRK"."MANDT"
		AND "BKPF"."AWKEY" = "VBRK"."VBELN"
	LEFT JOIN "BSEG" AS "BSEG" ON 1=1
		AND "BSEG"."MANDT" = "BKPF"."MANDT"
		AND "BSEG"."BELNR" = "BKPF"."BELNR"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "BKPF"."MANDT" = "USR02"."MANDT"
		AND "BKPF"."USNAM" = "USR02"."BNAME"
WHERE "BSEG"."AUGDT" IS NOT NULL;






/*
-- Activity: Change Sales Order
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY",
    "ACTIVITY",
    "EVENTTIME",
    "_SORTING",
    "USER_NAME",
    "USER_TYPE",
    "MANDT",
    "VBELN",
    "POSNR", )
SELECT 
    ,"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	 ,CASE 
		WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'A' THEN 'Pass Credit' 
		WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'B' THEN 'Set Credit Hold'
		WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'C' THEN 'Partially Pass Credit'  
        WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'D' THEN 'Release Credit Hold'
        WHEN "CDPOS"."FNAME" = 'LIFSK' AND "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 'Set Delivery Block'
 	    WHEN "CDPOS"."FNAME" = 'LIFSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 'Change Delivery Block' 
 	    WHEN "CDPOS"."FNAME" = 'LIFSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 'Remove Delivery Block'
        WHEN "CDPOS"."FNAME" = 'FAKSK' AND "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 'Set Billing Block'
 	    WHEN "CDPOS"."FNAME" = 'FAKSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 'Change Billing Block' 
 	    WHEN "CDPOS"."FNAME" = 'FAKSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 'Remove Billing Block'
 	 END AS  "ACTIVITY"
	, "CDPOS"."EVENTTIME" AS "EVENTTIME"
	,50 +
	CASE 
		WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'A' THEN 101
		WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'B' THEN 102
        WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'D' THEN 103
		WHEN "CDPOS"."FNAME" = 'CMGST' AND "CDPOS"."VALUE_NEW" = 'C' THEN 104
 	    WHEN "CDPOS"."FNAME" = 'LIFSK' AND "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 5
 	    WHEN "CDPOS"."FNAME" = 'LIFSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 6
 	    WHEN "CDPOS"."FNAME" = 'LIFSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 7
        WHEN "CDPOS"."FNAME" = 'FAKSK' AND "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 8
 	    WHEN "CDPOS"."FNAME" = 'FAKSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 9
 	    WHEN "CDPOS"."FNAME" = 'FAKSK' AND "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 10
 	 END AS "_SORTING"
	,"CDPOS"."USERNAME" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VABP"."MANDT" AS "MANDT"
	,"VABP"."VBELN" AS "VBELN"
	,"VABP"."POSNR" AS "POSNR"
FROM "VBAP"
	JOIN "CDPOS" ON
		"CDPOS"."MANDANT" =  "VABP"."MANDT" AND
		"CDPOS"."TABKEY" = "VABP"."VBELN" AND 
        "CDPOS"."TABNAME" IN ('VBUK', 'VBAK') 
	LEFT JOIN "USR02" AS "USR02" ON
		"USR02"."MANDT" = "CDPOS"."MANDANT" AND
		"USR02"."BNAME" = "CDPOS"."USERNAME"
    LEFT JOIN "TVLST"  ON 1=1
       AND "CDPOS"."MANDANT" = "TVLST"."MANDT"
       AND "CDPOS"."VALUE_NEW" = "TVLST"."LIFSP"
    LEFT JOIN "TVFST" ON 1=1
       AND "CDPOS"."MANDANT" = "TVFST"."MANDT"
       AND "CDPOS"."VALUE_OLD" = "TVFST"."FAKSP"
WHERE 
        (("CDPOS"."FNAME" = 'CMGST' AND 
        "CDPOS"."VALUE_NEW" IS NOT NULL) OR
        "CDPOS"."FNAME" IN ('LIFSK','FAKSK'))


-- Activity: Change Schedule Line
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY",
    "ACTIVITY",
    "EVENTTIME",
    "_SORTING",
    "USER_NAME",
    "USER_TYPE",
    "MANDT",
    "VBELN",
    "POSNR", )
SELECT
    ,"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
	, CASE 
		WHEN CDPOS.FNAME = 'EDATU' AND VBEP.BMENG = 0 THEN 'Change Requested Delivery Date'
        WHEN CDPOS.FNAME = 'EDATU' AND VBEP.BMENG > 0 THEN 'Change Confirmed Delivery Date'
 	    WHEN CDPOS.FNAME = 'MBDAT' THEN 'Change Material Availability Date'
 	    WHEN CDPOS.FNAME = 'WADAT' AND VBEP.BMENG = 0 THEN 'Change Requested Goods Issue Date'
 	    WHEN CDPOS.FNAME = 'WADAT' AND VBEP.BMENG > 0 THEN 'Change Confirmed Goods Issue Date'
        WHEN CDPOS.FNAME = 'BMENG' AND VBEP.BMENG = 0 THEN 'Change Requested Quantity'
		WHEN CDPOS.FNAME = 'BMENG' AND VBEP.BMENG > 0 THEN 'Change Confirmed Quantity'
 	  END AS  ACTIVITY
	, CDPOS."EVENTTIME"
	, CASE 
		WHEN CDPOS.FNAME = 'EDATU' AND VBEP.BMENG = 0 THEN 58
        WHEN CDPOS.FNAME = 'EDATU' AND VBEP.BMENG > 0 THEN 59
		WHEN CDPOS.FNAME = 'MBDAT' THEN 106
		WHEN CDPOS.FNAME = 'WADAT' AND VBEP.BMENG = 0 THEN 107
		WHEN CDPOS.FNAME = 'WADAT' AND VBEP.BMENG > 0 THEN 108
        WHEN CDPOS.FNAME = 'BMENG' AND VBEP.BMENG = 0 THEN 109
		WHEN CDPOS.FNAME = 'BMENG' AND VBEP.BMENG > 0 THEN 110
 	  END AS _SORTING
	, CDPOS.USERNAME AS USER_NAME
	, USR02.USTYP AS USER_TYPE
	, VBEP.MANDT AS MANDT
	, VBEP.VBELN AS VBELN
	, VBAP.POSNR AS POSNR
FROM "VBAP"
	INNER JOIN VBEP AS VBEP ON 1=1
		AND VBEP.VBELN = VBAP.VBELN 
		AND VBEP.POSNR = VBAP.POSNR	
        AND VBEP.MANDT = VBAP.MANDT
    INNER JOIN CDPOS ON 1=1
        AND CDPOS.MANDANT = VBEP.MANDT
	    AND CDPOS.TABKEY = VBEP.MANDT || VBEP.VBELN || VBEP.POSNR || VBEP.ETENR
	LEFT JOIN CDHDR ON 1=1
		AND CDHDR.CHANGENR = CDPOS.CHANGENR
	LEFT JOIN USR02 AS USR02 ON 1=1
		AND USR02.MANDT = CDHDR.MANDANT 
		AND USR02.BNAME = CDHDR.USERNAME;

-- Activity: Change Business Data
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY",
    "ACTIVITY",
    "EVENTTIME",
    "_SORTING",
    "USER_NAME",
    "USER_TYPE",
    "MANDT",
    "VBELN",
    "POSNR", )
SELECT
    ,"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
	,'Change ' || CASE 
		WHEN "CDPOS"."FNAME" = 'VSART' THEN 'Shipping Type'
		WHEN "CDPOS"."FNAME" = 'SDABW' THEN 'Freight Terms'
		WHEN "CDPOS"."FNAME" = 'ZTERM' THEN 'Payment Terms'
		WHEN "CDPOS"."FNAME" = 'INCO1' THEN 'Inco Terms (Part 1)'
		WHEN "CDPOS"."FNAME" = 'INCO2' THEN 'Inco Terms (Part 2)'
 	END AS  "ACTIVITY"
    ,CDHDR.UDATE  AS "EVENTTIME"
	,50 +
	CASE 
		WHEN "CDPOS"."FNAME" = 'BSTKD' THEN 1
		WHEN "CDPOS"."FNAME" = 'BSTDK' THEN 2
		WHEN "CDPOS"."FNAME" = 'VSART' THEN 3
		WHEN "CDPOS"."FNAME" = 'SDABW' THEN 4
		WHEN "CDPOS"."FNAME" = 'ZTERM' THEN 5
		WHEN "CDPOS"."FNAME" = 'INCO1' THEN 6
		WHEN "CDPOS"."FNAME" = 'INCO2' THEN 7
 	END AS "_SORTING"
	,"CDHDR"."USERNAME" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "VBAP"
	JOIN "CDPOS" AS "CDPOS" ON 1=1
	    AND "CDPOS"."MANDANT" = "VBAP"."MANDT"
	    AND "CDPOS"."TABKEY" = "VBAP"."MANDT" || "VBAP"."VBELN" || '000000'
        AND "CDPOS"."CHNGIND" = 'U'
        AND "CDPOS"."FNAME" IN ('VSART', 'SDABW', 'ZTERM', 'INCO1', 'INCO2')
        AND "CDPOS"."TABNAME" = 'VBKD' 
	JOIN "CDHDR" AS "CDHDR" ON 
		"CDPOS"."MANDANT" = "CDHDR"."MANDANT"
		AND "CDPOS"."OBJECTCLAS" = "CDHDR"."OBJECTCLAS"
		AND "CDPOS"."OBJECTID" = "CDHDR"."OBJECTID"
		AND "CDPOS"."CHANGENR" = "CDHDR"."CHANGENR"
	LEFT JOIN "USR02" AS "USR02" ON
		"USR02"."MANDT" = "CDHDR"."MANDANT" AND
		"USR02"."BNAME" = "CDHDR"."USERNAME";
*/