/*
Edit Notes
----------
1. ERDAT is now used as time stamp, which means ERZET is discarded
2. Follows VBAP, not VBAK
3. Removed German version of activities to simplify script
4. UDAT is now the combination of UDAT and UTIME
*/

DROP TABLE IF EXISTS "_CEL_O2C_VBAP_ACTIVITIES";
CREATE TABLE "_CEL_O2C_VBAP_ACTIVITIES" (
	"_CASE_KEY" VARCHAR(64)
    , "ACTIVITY" VARCHAR(200)
    , "EVENTTIME" DATETIME
    , "_SORTING" INTEGER
    , "USER_NAME" VARCHAR(100)
    , "USER_TYPE" VARCHAR(10)
    , "MANDT" VARCHAR(3)
    , "VBELN" VARCHAR(64)
    , "POSNR" INTEGER
);

-- Activity: Create Sales Order
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT 
    "VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
    ,'Create Sales Order' AS "ACTIVITY"
    ,"VBAK"."ERDAT" AS "EVENTTIME"
    ,10 AS "_SORTING"
    ,"VBAK"."ERNAM" AS "USER_NAME"
    ,"USR02"."USTYP" AS "USER_TYPE"
    ,"VBAP"."MANDT" AS "MANDT"
    ,"VBAP"."VBELN" AS "VBELN"
    ,"VBAP"."POSNR" AS "POSNR"
FROM "VBAP"
    LEFT JOIN "VBAK" ON 1=1
        AND "VBAP"."MANDT" = "VBAK"."MANDT"
        AND "VBAP"."VBELN" = "VBAK"."VBELN"
    LEFT JOIN "USR02" AS "USR02" ON 1=1
        AND "VBAK"."MANDT" = "USR02"."MANDT" 
        AND "VBAK"."ERNAM" = "USR02"."BNAME";

-- Activity: Generate Delivery Document
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
	,'Generate Delivery Document' AS "ACTIVITY"
	, "LIKP"."ERDAT" AS "EVENTTIME"
	, 20 AS "_SORTING"
	, "LIKP"."ERNAM" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	, "VBAP"."MANDT" AS "MANDT"
	, "VBAP"."VBELN" AS "VBELN"
	, "VBAP"."POSNR" AS "POSNR"
FROM "LIPS"
  LEFT JOIN "LIKP" AS "LIKP" ON 1=1
    AND "LIKP"."MANDT" = "LIPS"."MANDT"
    AND "LIKP"."VBELN" = "LIPS"."VBELN"
  LEFT JOIN "VBAP" AS "VBAP" ON 1=1
    AND "VBAP"."MANDT" = "LIPS"."MANDT"
    AND "VBAP"."VBELN" = "LIPS"."KDAUF"
    AND "VBAP"."POSNR" = "LIPS"."KDPOS"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "LIKP"."MANDT" = "USR02"."MANDT"
		AND "LIKP"."ERNAM" = "USR02"."BNAME";


-- Activity: Release Delivery
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
	,'Release Delivery' AS "ACTIVITY"
	, "CDHDR"."UDATE" AS "EVENTTIME"
	, 30 AS "_SORTING"
	, "CDHDR"."USERNAME" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	, "VBAP"."MANDT" AS "MANDT"
	, "VBAP"."VBELN" AS "VBELN"
	, "VBAP"."POSNR" AS "POSNR"
FROM "CDPOS"
	LEFT JOIN "LIPS" AS "LIPS" ON 1=1
    AND "CDPOS"."OBJECTID" = "LIPS"."MANDT" || "LIPS"."VBELN" || "LIPS"."POSNR"
  LEFT JOIN "VBAP" AS "VBAP" ON 1=1
    AND "VBAP"."MANDT" = "LIPS"."MANDT"
    AND "VBAP"."VBELN" = "LIPS"."KDAUF"
    AND "VBAP"."POSNR" = "LIPS"."KDPOS"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "CDHDR"."MANDANT" = "USR02"."MANDT"
		AND "CDHDR"."USERNAME" = "USR02"."BNAME"
WHERE "CDPOS"."TABNAME" = 'LIPS' AND "CDPOS"."FNAME" = 'ABART' AND "CDPOS"."VALUE_NEW" = 6;

-- Activity: Record Goods Issue (shipment)
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
 	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	,'Record Goods Issue' AS "ACTIVITY"
	,"MKPF"."SPE_BUDAT_UHR" AS "EVENTTIME"
	,40 AS "_SORTING"
	,"MKPF"."USNAM" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	, "VBAP"."MANDT" AS "MANDT"
	, "VBAP"."VBELN" AS "VBELN"
	, "VBAP"."POSNR" AS "POSNR"
FROM "MSEG"
	LEFT JOIN "MKPF" AS "MKPF" ON 1=1
		AND "MKPF"."MANDT" = "MSEG"."MANDT"
		AND "MKPF"."MBLNR" = "MSEG"."MBLNR"
  LEFT JOIN "VBAP" AS "VBAP" ON 1=1
    AND "VBAP"."MANDT" = "MSEG"."MANDT"
    AND "VBAP"."VBELN" = "MSEG"."KDAUF"
    AND "VBAP"."POSNR" = "MSEG"."KDPOS"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "MKPF"."MANDT" = "USR02"."MANDT"
		AND "MKPF"."USNAM" = "USR02"."BNAME";

-- Activity: Create Billing Document/Send Invoice
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
 	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	,'Send Invoice' AS "ACTIVITY"
	,"VBRK"."ERDAT" AS "EVENTTIME"
	,50 AS "_SORTING"
	,"VBRK"."ERNAM" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "VBRP"
  LEFT JOIN "VBAP" AS "VBAP" ON 1=1
    AND "VBAP"."MANDT" = "VBRP"."MANDT"
    AND "VBAP"."VBELN" = "VBRP"."AUBEL"
    AND "VBAP"."POSNR" = "VBRP"."AUPOS"
	LEFT JOIN "VBRK" AS "VBRK" ON 1=1
		AND "VBRK"."MANDT" = "VBRP"."MANDT"
		AND "VBRK"."VBELN" = "VBRP"."VBELN"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "VBRK"."MANDT" = "USR02"."MANDT"
		AND "VBRK"."ERNAM" = "USR02"."BNAME";


-- Activity: Receive Delivery Confirmation
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
	,'Receive Delivery Confirmation' AS "ACTIVITY"
	, "CDHDR"."UDATE" AS "EVENTTIME"
	, 60 AS "_SORTING"
	, "CDHDR"."USERNAME" AS "USER_NAME"
	, "USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "LIPS"
  LEFT JOIN "VBAP" AS "VBAP" ON 1=1
    AND "VBAP"."MANDT" = "LIPS"."MANDT"
    AND "VBAP"."VBELN" = "LIPS"."KDAUF"
    AND "VBAP"."POSNR" = "LIPS"."KDPOS"
	LEFT JOIN "CDPOS" AS "CDPOS" ON 1=1
		AND "CDPOS"."OBJECTID" = "LIPS"."MANDT" || "LIPS"."VBELN"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "CDHDR"."MANDANT" = "USR02"."MANDT"
		AND "CDHDR"."USERNAME" = "USR02"."BNAME"
WHERE "CDPOS"."TABNAME" = 'LIKP' AND "CDPOS"."FNAME" = 'SPE_ACC_APP_STS' AND "CDPOS"."VALUE_NEW" = 'C';

-- Activity: Clear Invoice
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
 	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	,'Clear Invoice' AS "ACTIVITY"
	,"BSEG"."AUGDT" AS "EVENTTIME"
	,70 AS "_SORTING"
	,"BKPF"."USNAM" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "BSEG"
	LEFT JOIN "VBAP" AS "VBAP" ON 1=1
		AND "VBAP"."MANDT" = "BSEG"."MANDT"
		AND "VBAP"."VBELN" = "BSEG"."VBEL2"
		AND "VBAP"."POSNR" = "BSEG"."POSN2"
	LEFT JOIN "BKPF" AS "BKPF" ON 1=1
		AND "BKPF"."MANDT" = "BSEG"."MANDT"
		AND "BKPF"."BELNR" = "BSEG"."BELNR"
	LEFT JOIN "USR02" AS "USR02" ON 1=1
		AND "BKPF"."MANDT" = "USR02"."MANDT"
		AND "BKPF"."USNAM" = "USR02"."BNAME"
WHERE "BSEG"."AUGDT" IS NOT NULL;


-- Avtivity: Set/Remove Billing Block
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
 	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	,CASE 
		WHEN "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 'Set Billing Block'
		WHEN "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 'Remove Billing Block'
	END AS "ACTIVITY"
	,"CDHDR"."UDATE" AS "EVENTTIME"
	,30 +
	CASE 
		WHEN "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 1 -- 'Set Billing Block'
		WHEN "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 11 -- 'Remove Billing Block'
	END AS "_SORTING"
	,"CDHDR"."USERNAME" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "CDPOS"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."MANDANT" = "CDPOS"."MANDANT"
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "VBAK" AS "VBAK" ON 1=1
		AND "VBAK"."MANDT" = "CDHDR"."MANDANT"
		AND "VBAK"."VBELN" = "CDHDR"."OBJECTID"
	LEFT JOIN "VBAP" AS "VBAP" ON 1=1
		AND "VBAP"."MANDT" = "VBAK"."MANDT"
		AND "VBAP"."VBELN" = "VBAK"."VBELN"
  LEFT JOIN "USR02" AS "USR02" ON 1=1
    AND "USR02"."MANDT" = "CDHDR"."MANDANT"
    AND "USR02"."BNAME" = "CDHDR"."USERNAME"
WHERE "CDPOS"."TABNAME" = 'VBAK'
	AND "CDPOS"."FNAME" = 'FAKSK';

-- Avtivity: Set/Remove Delivery Block
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
 	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	,CASE 
		WHEN "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 'Set Delivery Block'
		WHEN "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 'Remove Delivery Block'
	END AS "ACTIVITY"
	,"CDHDR"."UDATE" AS "EVENTTIME"
	,20 +
	CASE 
		WHEN "CDPOS"."VALUE_OLD" IS NULL AND "CDPOS"."VALUE_NEW" IS NOT NULL THEN 1 -- 'Set Delivery Block'
		WHEN "CDPOS"."VALUE_OLD" IS NOT NULL AND "CDPOS"."VALUE_NEW" IS NULL THEN 2 -- 'Remove Delivery Block'
	END AS "_SORTING"
	,"CDHDR"."USERNAME" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "CDPOS"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."MANDANT" = "CDPOS"."MANDANT"
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "VBAK" AS "VBAK" ON 1=1
		AND "VBAK"."MANDT" = "CDHDR"."MANDANT"
		AND "VBAK"."VBELN" = "CDHDR"."OBJECTID"
	LEFT JOIN "VBAP" AS "VBAP" ON 1=1
		AND "VBAP"."MANDT" = "VBAK"."MANDT"
		AND "VBAP"."VBELN" = "VBAK"."VBELN"
  LEFT JOIN "USR02" AS "USR02" ON 1=1
    AND "USR02"."MANDT" = "CDHDR"."MANDANT"
    AND "USR02"."BNAME" = "CDHDR"."USERNAME"
WHERE "CDPOS"."TABNAME" = 'VBAK'
	AND "CDPOS"."FNAME" = 'LIFSK';

-- Avtivity: Cancel/Return Order
INSERT INTO "_CEL_O2C_VBAP_ACTIVITIES" (
    "_CASE_KEY"
    , "ACTIVITY"
    , "EVENTTIME"
    , "_SORTING"
    , "USER_NAME"
    , "USER_TYPE"
    , "MANDT"
    , "VBELN"
    , "POSNR" 
)
SELECT
 	"VBAP"."MANDT" || "VBAP"."VBELN" || "VBAP"."POSNR" AS "_CASE_KEY"
 	,CASE 
		WHEN "CDPOS"."VALUE_NEW" = 'H' THEN 'Return Order'
		WHEN "CDPOS"."VALUE_NEW" = 'CANCELLED' THEN 'Cancel Order'
	END AS "ACTIVITY"
	,"CDHDR"."UDATE" AS "EVENTTIME"
	,100 +
	CASE 
		WHEN "CDPOS"."VALUE_NEW" = 'H' THEN 1 -- 'Return Order'
		WHEN "CDPOS"."VALUE_NEW" = 'CANCELLED' THEN 2 -- Cancel Order'
	END AS "_SORTING"
	,"CDHDR"."USERNAME" AS "USER_NAME"
	,"USR02"."USTYP" AS "USER_TYPE"
	,"VBAP"."MANDT" AS "MANDT"
	,"VBAP"."VBELN" AS "VBELN"
	,"VBAP"."POSNR" AS "POSNR"
FROM "CDPOS"
	LEFT JOIN "CDHDR" AS "CDHDR" ON 1=1
		AND "CDHDR"."MANDANT" = "CDPOS"."MANDANT"
		AND "CDHDR"."CHANGENR" = "CDPOS"."CHANGENR"
	LEFT JOIN "VBAK" AS "VBAK" ON 1=1
		AND "VBAK"."MANDT" = "CDHDR"."MANDANT"
		AND "VBAK"."VBELN" = "CDHDR"."OBJECTID"
	LEFT JOIN "VBAP" AS "VBAP" ON 1=1
		AND "VBAP"."MANDT" = "VBAK"."MANDT"
		AND "VBAP"."VBELN" = "VBAK"."VBELN"
  LEFT JOIN "USR02" AS "USR02" ON 1=1
    AND "USR02"."MANDT" = "CDHDR"."MANDANT"
    AND "USR02"."BNAME" = "CDHDR"."USERNAME"
WHERE "CDPOS"."TABNAME" = 'VBAK'
	AND "CDPOS"."FNAME" = 'VBTYP';