import random
from datetime import datetime, timedelta

customers = {
    "Tasty Bites Co.": {},
    "Brewmaster's Blend": {},
    "Crispy Cravings": {},
    "Sips & Savories": {},
    "Gourmet Delights Inc.": {},
    "Flavor Fusion Foods": {},
    "Café Elegance": {},
    "FreshNosh": {},
    "SodaStreamers": {},
    "Sweets & Sips": {},
    "Gastronomy Galore": {},
    "Nectar Nook": {},
    "Spice & Savor": {},
    "Wholesome Treats": {},
    "Munchies Magic": {},
    "Siplicity Drinks": {},
    "Foodie Fantasy": {},
    "Yummy Morsels": {},
    "Baker's Bliss Co.": {},
    "ThirstQuencher": {},
    "Epicurean Eats": {},
    "Gusto Gourmets": {},
    "Beverage Bliss": {},
    "Taste Troupe": {},
    "ChocoCharm Confections": {},
    "SavorStreet": {},
    "Culinary Crafters": {},
    "BrewBurst Beverages": {},
    "NoshNation": {},
    "Gastronomic Gather": {},
}

users = {
    "Alice Johnson": 'A',
    "Bob Smith": 'A',
    "Carol Davis": 'A',
    "David Williams": 'A',
    "Emily Brown": 'A',
    "Frank Taylor": 'A',
    "Grace Moore": 'A',
    "Henry Clark": 'A',
    "Isabella Lewis": 'A',
    "Jack Hall": 'A',
    "Karen Lee": 'A',
    "Liam Mitchell": 'A',
    "Mia Anderson": 'A',
    "Noah Harris": 'A',
    "Olivia White": 'A',
    "Peter Turner": 'A',
    "Sophia Martin": 'A',
    "Thomas Walker": 'A',
    "Victoria Baker": 'A',
    "William Turner": 'A',
    "BATCH_JOB": 'B',
}

mandt = 'SC1'

times = {
    'customer_create_start': datetime(2009, 1, 1),
    'salesorder_create_end': datetime(2019, 12, 31),
}

shipping_conditions = [
    {"name": "Standard Delivery",},
    {"name": "Express Delivery",},
    {"name": "Airfreight",},
    {"name": "Sea Freight",},
    {"name": "Rail Transport",},
    {"name": "Truck Transport",},
    {"name": "Courier Service",},
    {"name": "Pickup by Customer",},
    {"name": "Post Office",},
    {"name": "Local Delivery",},
    {"name": "Same-Day Delivery",},
    {"name": "Next-Day Delivery",},
    {"name": "Temperature-Sensitive",},
    {"name": "Hazardous Materials",},
    {"name": "Special Handling",},
    {"name": "Drop Ship",},
    {"name": "International Shipping",},
]

materials = {
    "Rice": {"price": 2.99},
    "Coffee": {"price": 5.49},
    "Tea": {"price": 3.99},
    "Soda": {"price": 1.49},
    "Bottled Water": {"price": 0.99},
    "Chips": {"price": 2.79},
    "Cookies": {"price": 3.49},
    "Candy": {"price": 1.99},
    "Ice Cream": {"price": 4.99},
    "Frozen Pizza": {"price": 5.99},
    "Canned Soup": {"price": 1.79},
    "Honey": {"price": 4.29},
    "Peanut Butter": {"price": 3.29},
    "Jam": {"price": 2.99},
    "Canned Vegetables": {"price": 1.69},
    "Frozen Vegetables": {"price": 2.49},
    "Olive Oil": {"price": 6.99},
    "Vinegar": {"price": 2.19},
    "Balsamic Vinegar": {"price": 4.99},
    "Wine": {"price": 9.99},
    "Beer": {"price": 1.99},
    "Soy Sauce": {"price": 2.29},
    "Worcestershire Sauce": {"price": 2.79},
    "Pickles": {"price": 2.49},
    "Olives": {"price": 3.29},
    "Canned Tuna": {"price": 1.99},
    "Canned Salmon": {"price": 3.99},
    "Dried Fruits": {"price": 4.49},
    "Nuts": {"price": 5.99},
    "Hamburger Buns": {"price": 2.49},
    "Hot Dog Buns": {"price": 2.29},
    "Mustard": {"price": 1.79},
    "Barbecue Sauce": {"price": 2.99},
    "Salsa": {"price": 2.49},
    "Tortilla Chips": {"price": 2.79},
    "Sour Cream": {"price": 1.99},
    "Cottage Cheese": {"price": 3.29},
    "Pudding": {"price": 1.49},
    "Cereal Bars": {"price": 3.49},
    "Oatmeal": {"price": 2.99},
    "Frozen Burritos": {"price": 4.49},
    "Frozen Dinners": {"price": 3.99},
    "Sausages": {"price": 5.49},
    "Muffins": {"price": 2.79},
    "Bagels": {"price": 2.49},
    "Donuts": {"price": 1.99},
    "Canned Fruit": {"price": 2.29},
    "Fruit Cups": {"price": 2.99},
    "Almond Milk": {"price": 3.49},
    "Coconut Water": {"price": 2.79},
    "Trail Mix": {"price": 4.99}
}
