import random
from datetime import datetime, timedelta

company_names = [
    {"name": "Tasty Bites Co.", "credit_worthyness": 0.7},
    {"name": "Brewmaster's Blend", "credit_worthyness": 0.5},
    {"name": "Crispy Cravings", "credit_worthyness": 0.3},
    {"name": "Sips & Savories", "credit_worthyness": 0.3},
    {"name": "Gourmet Delights Inc.", "credit_worthyness": 0.2},
    {"name": "Flavor Fusion Foods", "credit_worthyness": 0.4},
    {"name": "Café Elegance", "credit_worthyness": 0.6},
    {"name": "FreshNosh", "credit_worthyness": 0.7},
    {"name": "SodaStreamers", "credit_worthyness": 0.7},
    {"name": "Sweets & Sips", "credit_worthyness": 0.8},
    {"name": "Gastronomy Galore", "credit_worthyness": 0.4},
    {"name": "Nectar Nook", "credit_worthyness": 0.4},
    {"name": "Spice & Savor", "credit_worthyness": 0.6},
    {"name": "Wholesome Treats", "credit_worthyness": 0.4},
    {"name": "Munchies Magic", "credit_worthyness": 0.8},
    {"name": "Siplicity Drinks", "credit_worthyness": 0.8},
    {"name": "Foodie Fantasy", "credit_worthyness": 0.7},
    {"name": "Yummy Morsels", "credit_worthyness": 0.9},
    {"name": "Baker's Bliss Co.", "credit_worthyness": 0.9},
    {"name": "ThirstQuencher", "credit_worthyness": 0.7},
    {"name": "Epicurean Eats", "credit_worthyness": 0.8},
    {"name": "Gusto Gourmets", "credit_worthyness": 0.5},
    {"name": "Beverage Bliss", "credit_worthyness": 0.4},
    {"name": "Taste Troupe", "credit_worthyness": 0.4},
    {"name": "ChocoCharm Confections", "credit_worthyness": 0.2},
    {"name": "SavorStreet", "credit_worthyness": 0.1},
    {"name": "Culinary Crafters", "credit_worthyness": 0.7},
    {"name": "BrewBurst Beverages", "credit_worthyness": 0.4},
    {"name": "NoshNation", "credit_worthyness": 0.7},
    {"name": "Gastronomic Gather", "credit_worthyness": 0.8},
]

users = [
    "Alice Johnson",
    "Bob Smith",
    "Carol Davis",
    "David Williams",
    "Emily Brown",
    "Frank Taylor",
    "Grace Moore",
    "Henry Clark",
    "Isabella Lewis",
    "Jack Hall",
    "Karen Lee",
    "Liam Mitchell",
    "Mia Anderson",
    "Noah Harris",
    "Olivia White",
    "Peter Turner",
    "Sophia Martin",
    "Thomas Walker",
    "Victoria Baker",
    "William Turner"
]

mandt = 'SC1'

times = {
    'customer_create_start': datetime(2009, 1, 1),
    'salesorder_create_end': datetime(2019, 12, 31),
}

shipping_conditions = [
    {"name": "Standard Delivery",},
    {"name": "Express Delivery",},
    {"name": "Airfreight",},
    {"name": "Sea Freight",},
    {"name": "Rail Transport",},
    {"name": "Truck Transport",},
    {"name": "Courier Service",},
    {"name": "Pickup by Customer",},
    {"name": "Post Office",},
    {"name": "Local Delivery",},
    {"name": "Same-Day Delivery",},
    {"name": "Next-Day Delivery",},
    {"name": "Temperature-Sensitive",},
    {"name": "Hazardous Materials",},
    {"name": "Special Handling",},
    {"name": "Drop Ship",},
    {"name": "International Shipping",},
]

material_names = [
    {"name": "Rice", "availability": 0.7, "price": 6},
    {"name": "Coffee", "availability": 0.8, "price": 5},
    {"name": "Tea", "availability": 0.8, "price": 3},
    {"name": "Soda", "availability": 0.8, "price": 4},
    {"name": "Bottled Water", "availability": 0.6, "price": 3.3},
    {"name": "Chips", "availability": 0.4, "price": 4.5},
    {"name": "Cookies", "availability": 0.3, "price": 3},
    {"name": "Candy", "availability": 0.6, "price": 1.1},
    {"name": "Ice Cream", "availability": 0.1, "price": 6.2},
    {"name": "Frozen Pizza", "availability": 0.2, "price": 6.8},
    {"name": "Canned Soup", "availability": 0.3, "price": 5.5},
    {"name": "Honey", "availability": 0.4, "price": 7.8},
    {"name": "Peanut Butter", "availability": 0.7, "price": 5},
    {"name": "Jam", "availability": 0.7, "price": 7.7},
    {"name": "Canned Vegetables", "availability": 0.4, "price": 4},
    {"name": "Frozen Vegetables", "availability": 0.3, "price": 2},
    {"name": "Olive Oil", "availability": 0.9, "price": 12},
    {"name": "Vinegar", "availability": 0.7, "price": 9},
    {"name": "Balsamic Vinegar", "availability": 0.7, "price": 8},
    {"name": "Wine", "availability": 0.9, "price": 15},
    {"name": "Beer", "availability": 0.9, "price": 6.4},
    {"name": "Soy Sauce", "availability": 0.6, "price": 6.6},
    {"name": "Worcestershire Sauce", "availability": 0.5, "price": 11.2},
    {"name": "Pickles", "availability": 0.4, "price": 8},
    {"name": "Olives", "availability": 0.6, "price": 9.4},
    {"name": "Canned Tuna", "availability": 0.9, "price": 7.5},
    {"name": "Canned Salmon", "availability": 0.9, "price": 8.3},
    {"name": "Dried Fruits", "availability": 0.4, "price": 6.3},
    {"name": "Nuts", "availability": 0.5, "price": 4},
    {"name": "Hamburger Buns", "availability": 0.3, "price": 2.1},
    {"name": "Hot Dog Buns", "availability": 0.1, "price": 1.2},
    {"name": "Mustard", "availability": 0.8, "price": 7.8},
    {"name": "Barbecue Sauce", "availability": 0.6, "price": 8},
    {"name": "Salsa", "availability": 0.2, "price": 8.3},
    {"name": "Tortilla Chips", "availability": 0.3, "price": 2.4},
    {"name": "Sour Cream", "availability": 0.9, "price": 4.56},
    {"name": "Cottage Cheese", "availability": 0.6, "price": 26},
    {"name": "Pudding", "availability": 0.4, "price": 7},
    {"name": "Cereal Bars", "availability": 0.8, "price": 2.5},
    {"name": "Oatmeal", "availability": 0.7, "price": 5},
    {"name": "Frozen Burritos", "availability": 0.2, "price": 3},
    {"name": "Frozen Dinners", "availability": 0.2, "price": 2},
    {"name": "Sausages", "availability": 0.5, "price": 4},
    {"name": "Muffins", "availability": 0.4, "price": 2},
    {"name": "Bagels", "availability": 0.4, "price": 1.5},
    {"name": "Donuts", "availability": 0.4, "price": 4},
    {"name": "Canned Fruit", "availability": 0.7, "price": 6},
    {"name": "Fruit Cups", "availability": 0.4, "price": 7},
    {"name": "Almond Milk", "availability": 0.4, "price": 4},
    {"name": "Coconut Water", "availability": 0.3, "price": 7},
    {"name": "Trail Mix", "availability": 0.5, "price": 5},
]