from datetime import datetime, timedelta

company_names = [
    'ARCAM Corporation',
    'Ace Chemicals',
    "Ace o' Clubs",
    'Acme Corporation',
    'Adipose Industries',
    'Advanced Idea Mechanics',
    'Alchemax',
    'AmerTek',
    'Big Belly Burger',
    'Blaze Comics',
    'Bonk Business',
    'Bonsai Kitten',
    'Brand Corporation',
    'Breakages',
    'Buy More',
    'Buy n Large',
    'BuyTigers.com',
    'CHOAM',
    "Clothes Over Bro's",
    'ConHugeCo',
    'Consumer Recreation Services',
    'Contoso',
    'Cross Technological Enterprises',
    'Crosstime Traffic',
    'Crudgington Brewery',
    'Daedalus Research',
    'Daggett Industries',
    'Dr. Zeus Inc.',
    'Dream Park',
    'Dunder Mifflin',
    'Fantastic Four Incorporated',
    'GameCenter CX',
    'General Products',
    'Global Digital News',
    'Golden Goblin Press',
    'GothCorp',
    'Halo Corporation',
    "Haly's Circus",
    'Haspel Corporation',
    "Hooper's Store",
    'Iceberg Lounge',
    'Jabot Cosmetics',
    'Kitchen Table International',
    'Kord Enterprises',
    "L'Desh Fresh",
    'Landau',
    'LexCorp',
    'Life Foundation',
    'List of fictional brewers',
    'Mammoth Studios',
    'ManBeef.com',
    'Management Corporation',
    'Massive Dynamic',
    'McMahon and Tate',
    'Media in The Simpsons',
    'Megacorporation',
    'Michael Scott Paper Company',
    'Monsters',
    'National Motors Corporation',
    'Nologo Corporation',
    'Octan',
    'Oscorp',
    'Paper Street Soap Co.',
    'Parker Industries',
    'Phua Chu Kang Pte Ltd',
    'Power Broker',
    'Queen Industries',
    'RAMJAC',
    'Red Bedroom Records',
    'Roxxon Energy Corporation',
    'Santini Air',
    'Seburo',
    'Shadrack & Duxbury',
    'Sloane Curtis Advertising',
    'Soder Cola',
    'Stagg Enterprises',
    'Stark Industries',
    "Struan's",
    'The Lightman Group',
    'The Monster Maker',
    'The World Gone Mad',
    'Tyrell Corporation',
    'U.S. Robots and Mechanical',
    'Vaillante',
    'Wallenquist Organization',
    'Wayne Enterprises',
    'Weyland-Yutani Corporation',
    'World Company',
    'Yoyodyne'
]

users = {
'Alejandro Atwood': 'A',
'Alfonso Wernick': 'A',
'Alvin Malin': 'A',
'Anna Hulings': 'A',
'Arletta Landen': 'A',
'BATCH_JOB': 'B',
'Bradford Amarante': 'A',
'Ceola Harry': 'A',
'Cher Ehrmann': 'A',
'Cherryl Vandine': 'A',
'Dalila Proehl': 'A',
'Dominica Kirkley': 'A',
'Emilio Sones': 'A',
'Emmie Schuldt': 'A',
'Felice Cover': 'A',
'Francina Bevington': 'A',
'Gloria Ashburn': 'A',
'Irene Llanas': 'A',
'Jamie Mcclellan': 'A',
'Jena Jeans': 'A',
'Karri Ptacek': 'A',
'Kenia Romine': 'A',
'Kristen Eckhoff': 'A',
'Lang Winkler': 'A',
'Lavonna Haymon': 'A',
'Lawerence Pintor': 'A',
'Leontine Sifford': 'A',
'Lessie Scheck': 'A',
'Lillian Wheaton': 'A',
'Lora Rieder': 'A',
'Lucina Boyers': 'A',
'Luisa Solar': 'A',
'Marcela Ye': 'A',
'Margene Hamil': 'A',
'Marita Creagh': 'A',
'Melissia Kreidler': 'A',
'Orville Sheilds': 'A',
'Rachel Onorato': 'A',
'Rona Hennis': 'A',
'Roy Ortego': 'A',
'Sharyn Laxton': 'A',
'Suellen Noecker': 'A',
'Summer Fusaro': 'A',
'Tasia Snelgrove': 'A',
'Toby Narvaez': 'A',
'Tyree Decastro': 'A',
'Ward Weckerly': 'A',
'Yanira Gottfried': 'A',
}

mandt = 'SC1'

times = {
    'customer_create_start': datetime(2009, 1, 1),
    
    'salesorder_create_end': datetime(2019, 12, 31),
}

shipping_conditions = [
    "Standard Delivery",
    "Express Delivery",
    "Airfreight",
    "Sea Freight",
    "Rail Transport",
    "Truck Transport",
    "Courier Service",
    "Pickup by Customer",
    "Post Office",
    "Local Delivery",
    "Same-Day Delivery",
    "Next-Day Delivery",
    "Temperature-Sensitive",
    "Hazardous Materials",
    "Special Handling",
    "Drop Ship",
    "International Shipping",
    "Standard Pallet",
    "Third-Party Logistics (3PL)"
]

material_names = [
    'AeroSynth',
    'Aeroclay',
    'Aerogelium',
    'Aeroglass',
    'Aeroplastic',
    'Alumiflex',
    'Alumitex',
    'Alumithread',
    'Alumiwood',
    'BioFoam',
    'BioNylon',
    'BioSteel',
    'BioStone',
    'BioSynth',
    'Biocore',
    'Biofoam',
    'Biogel',
    'Biothread',
    'Biowood',
    'CarboSilk',
    'Carbonova',
    'Carboprene',
    'Durafiber',
    'Duraflex',
    'Duraglass',
    'DynaMica',
    'DynaPlast',
    'DynaTex',
    'Dynawood',
    'Ecolith',
    'Fibrilith',
    'Fibrinex',
    'Fibrinova',
    'FlexiCarbon',
    'FlexiFoam',
    'FlexiSilk',
    'Flexiprene',
    'GraphiFoam',
    'GraphiSteel',
    'GraphiTex',
    'GraphiWood',
    'Graphiflex',
    'Lumiglass',
    'Magniflex',
    'Metalfiber',
    'Metalline',
    'Metallite',
    'Metalloplast',
    'Metallura',
    'NanoFlex',
    'NanoWood',
    'Nanoclay',
    'Nanocore',
    'Nanogel',
    'NeoFlex',
    'NeoFoam',
    'NeoGlass',
    'Neofiber',
    'Plastiflex',
    'Plastistone',
    'Plastiweave',
    'Polycore',
    'Polymetal',
    'Polyplast',
    'Polysilk',
    'Polytex',
    'Polywood',
    'Quantumetal',
    'Quantumflex',
    'Quantumtex',
    'Quicksilicate',
    'Quicksilva',
    'Quicksilvate',
    'SilicoSteel',
    'Silicofoam',
    'Silicogel',
    'Siliconova',
    'Silicowood',
    'Silvertex',
    'SynthiCore',
    'SynthiTex',
    'SynthiWood',
    'Synthifiber',
    'Synthiglass',
    'TechnoWood',
    'Technofiber',
    'Technothread',
    'Thermoflex',
    'Thermogel',
    'Thermoglass',
    'Thermoplast',
    'VibraSteel',
    'Vibrafoam',
    'VibroSteel',
    'Vibrocrete',
    'XenoPlastic',
    'XenoSilk',
    'XenoTex',
    'Xylogel',
    'Batmobile'
]